// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2X7emXfn7oBq4wJF5kH5ACcAO6ucSQzg',
    appId: '1:545150671667:web:b7b373d0eeb68c8e097c46',
    messagingSenderId: '545150671667',
    projectId: 'smart-farm-sheba',
    authDomain: 'smart-farm-sheba.firebaseapp.com',
    storageBucket: 'smart-farm-sheba.firebasestorage.app',
    measurementId: 'G-G92YQDTZS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLvPIC3kCXoxky-kbLsDRxUcw4WKKrWY',
    appId: '1:545150671667:android:85b5ba936239198a097c46',
    messagingSenderId: '545150671667',
    projectId: 'smart-farm-sheba',
    storageBucket: 'smart-farm-sheba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2X7emXfn7oBq4wJF5kH5ACcAO6ucSQzg',
    appId: '1:545150671667:web:7635b14d174c21d3097c46',
    messagingSenderId: '545150671667',
    projectId: 'smart-farm-sheba',
    authDomain: 'smart-farm-sheba.firebaseapp.com',
    storageBucket: 'smart-farm-sheba.firebasestorage.app',
    measurementId: 'G-4G5X873SG9',
  );
}
